export default {
	not_signed_in: 'Nejste přihlášen',
	unknown_error: 'Nastala neočekávaná chyba',
	add_review: 'Přidat hodnocení',
	description: 'Popis',
	cancel: 'Zrušit',
	submit: 'Odeslat',
	cs: 'Čeština',
	en: 'Angličtina',
	home: 'Domů',
	play: 'Hrát',
	about: 'O nás',
	reviews: 'Hodnocení',
	login: 'Přihlásit',
	logout: 'Odhlásit',
	delete: 'Smazat',
	tie_is: 'Remíza',
	winner_is: 'Vyhrál:',
	player_is: 'Na tahu:',
	required: 'Požadováno',
	welcome: 'Vítej',
	start: 'Začít',
	recent_games: 'Nedávné hry:',
	email: 'Email',
	password: 'Heslo',
	sign_up: 'Registrovat se',
	sign_in: 'Přihlásit se',
	not_found: 'Stránka nenalezena',
	not_found_text: 'Oops, vyzerá to že tato stránka neexistuje',
	user_reviews: 'Uživatelská hodnocení:'
};
