export default {
	not_signed_in: 'You are not signed in',
	unknown_error: 'Unknown error occurred',
	add_review: 'Add a review',
	description: 'Description',
	cancel: 'Cancel',
	submit: 'Submit',
	cs: 'Czech',
	en: 'English',
	home: 'Home',
	play: 'Play',
	about: 'About',
	reviews: 'Reviews',
	login: 'Login',
	logout: 'Logout',
	delete: 'Delete',
	tie_is: "It's a tie",
	winner_is: 'Winner is:',
	player_is: 'Next player:',
	required: 'Required',
	welcome: 'Welcome',
	start: "Let's start",
	recent_games: 'Recent games:',
	email: 'Email',
	password: 'Password',
	sign_up: 'SignUp',
	sign_in: 'SignIn',
	not_found: 'Not Found',
	not_found_text: 'Oops, looks like this page does not exist',
	user_reviews: 'User reviews:'
};
